Feat/turtlebot3c image
ubuntu-robotics/turtlebot3c-ubuntu-core pull request #1
Opened 2024-06-18 15:01 UTC by Guillaumebeuzeboc

2024-07-30 16:21 UTC, artivis requested changes

2024-07-30 16:21 UTC, artivis commented on README.md
> +The image will contain the TurtleBot3c snaps:
```suggestion
The image contains the TurtleBot3c snaps:
```

2024-07-30 16:21 UTC, artivis commented on README.md
> +The image will create a Hotspot called `turtlebot3c`
```suggestion
The image creates a Hotspot called `turtlebot3c`
```

2024-07-30 16:21 UTC, artivis commented on README.md
> +the robot will be available at `turtelbot3c.local`
```suggestion
the robot is available on the network as `turtelbot3c.local`.
Mind that you need avahi installed on your remote machine, see e.g. `snap install avahi`.
```

2024-07-30 16:21 UTC, artivis commented on README.md
> +All the ROS topics are available on the `ROS_MASTER_URI`:
```suggestion
Remember to set up the `ROS_MASTER_URI` to point to the robot:
```

2024-07-30 16:21 UTC, artivis commented on README.md
> +Build the gadget snap with snapcraft
```suggestion
Build the gadget snap with snapcraft:
```

2024-07-30 16:21 UTC, artivis commented on pi-gadget/gadget.yaml
> +  pi:
Let's rename this volume since it also sets the name of the generated image.
E.g. `turtlebot3c`

2024-07-30 16:21 UTC, artivis commented on pi-gadget/snapcraft.yaml
> +  Module 3, and the Compute Module 3+ universally.
Please update this?

2024-07-30 16:21 UTC, artivis commented on turtlebot3c-model.json
> +    "grade": "dangerous",
Why is it dangerous?

2024-07-30 16:21 UTC, artivis commented on turtlebot3c-model.json
> +        { "name": "pi-kernel",
Missing line break.

2024-08-06 15:13 UTC, Guillaumebeuzeboc commented on turtlebot3c-model.json
> +    "grade": "dangerous",
because the gadget snap is. we cannot upload and get approved a gadget snap on the store.

2024-08-06 15:15 UTC, Guillaumebeuzeboc commented on pi-gadget/gadget.yaml
> +  pi:
Should this also be mentioned in the tutorial? Since it's most likely a bug does it make sense to do that?

2024-08-09 08:01 UTC, artivis commented on pi-gadget/gadget.yaml
> +  pi:
Nop no need.

2024-08-22 09:44 UTC, artivis approved these changes

2024-08-22 10:05 UTC, merged